### ISSUE TITLE
Add Python 2/3 compatibility module

### ISSUE THREAD

**Issue by bworrell** [CybOXProject/mixbox#1]
Add the Python 2/3 `compat.py` module used in https://github.com/CybOXProject/python-cybox/pull/228 here, since it'll likely find its way into python-stix and python-maec as well.

**Comment by gtback** [comment]
I removed quite a bit from the `cybox.compat` module, since I'm using `six` directly in most places. What's left probably isn't that useful outside of CybOX, so I'm going to close this for now. If there is code in there that ends up being more generally useful, I'm happy to add it to `mixbox`.
