### ISSUE TITLE
LICENSE.txt is missing

### ISSUE THREAD

**Issue by glaslos** [CybOXProject/mixbox#15]
See https://github.com/CybOXProject/mixbox/blob/master/setup.py#L4

**Comment by gtback** [comment]
Thanks, @glaslos Should be fixed now. Just curious, are you trying to do something with mixbox or were you just looking around? Mixbox is still under heavy development and is definitely alpha-grade :smile:

**Comment by glaslos** [comment]
It was a requirement for CybOX and I needed the license information.
