### ISSUE TITLE
weakrefmethod module incompatible with Python 3

### ISSUE THREAD

**Issue by bworrell** [CybOXProject/mixbox#23]
The `mixbox.signals` module uses `WeakMethod`, which was introduced in Python 3.4. For earlier versions of Python, we import `WeakMethod` from the external `weakrefmethod` module. 

The `weakrefmethod` module is not compatible with Python 3 due to a relative import of its internal `_version` module. As such, we get CI failures on Python 3.2 and Python 3.3.

One solution may be to copy the `weakrefmethod` module into the `vendor` package and alter our imports accordingly.

**Comment by gtback** [comment]
Fixed by #28
