### ISSUE TITLE
How to parser incidents useing mixbox

### ISSUE THREAD

**Issue by PintoArt** [CybOXProject/mixbox#40]
Hi
I am new for the STIX format.
I am trying to find out how can i parser,and  isolate the incidents from the STIX (xml) file .
Is there any example for that except root/tag
Thank you fr your help

**Comment by gtback** [comment]
Hi, @PintoArt . Thanks for the question, and welcome to the STIX community!

It might help to start by looking at [this example](https://stixproject.github.io/documentation/idioms/incident-vs-indicator/#as-incidents) (look under "Python Consumer"), as well as some of the other idioms on the stixproject.github.io site. 

`mixbox` is an internal library used by [python-stix](https://github.com/STIXProject/python-stix), so issues with parsing STIX (in Python) should go there instead. GitHub issues are best for reporting bugs or requesting new features in the libraries, and not as great for asking general questions.

You'll also get more people to see your question if you ask the **[[cti-users] list](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=cti#feedback)**, which is more of a user forum for people using STIX and TAXII (including these libraries). 

I'm going to close this issue, but please continue asking questions and learning more about STIX.
