### ISSUE TITLE
Add a cache module

### ISSUE THREAD

**Issue by bworrell** [CybOXProject/mixbox#7]
This would likely contain code similar to that found in [this](https://github.com/STIXProject/python-stix/commit/085b486a02985da48a3864d00896732b6d6e78b0) commit and enable fast lookup of objects by ID.

**Comment by bworrell** [comment]
Added the module in 6b34da8f88556fad9ac6624aa80e8c7ca0da9a18 and tests in c802df34068c1985223c42549739e607f7a27752. 

Nothing implements this code yet, so it may need to change considerably as we start to roll out the integration of mixbox. I'm going to keep this open until we actually start to use this code.

**Comment by gtback** [comment]
Closed by #11
